spring.application.name=Tikito

# Load local environment variables
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=36000000

<<<<<<< HEAD
cloudinary.cloud-name=gelhmg2g
cloudinary.api-key=	694738865914538
cloudinary.api-secret=rVK84Q0erRXSooWYbDtZiLrSmeE
=======
upload.path=${UPLOAD_PATH}s
>>>>>>> 9c112bdc6c4f8f8fb395358b315aeb6f36a7ff29


# For Email Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# For razorpay
razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}
